services:
#  app:
#    build: .
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#      DATASOURCE_USERNAME: postgres
#      DATASOURCE_PASSWORD: postgres
#    ports:
#      - "8080:8080"
#    volumes:
#      - template-config:/app/config
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -d postgres -U postgres"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
#  template-config:
#    external: true



