package ru.itmo.practicemanager.entity;

public enum CheckStatus {
    OK, COMPANY_NOT_FOUND, ACTIVITY_NOT_SUITABLE, API_ERROR, JSON_PARSING_ERROR, LOCATION_NOT_SUITABLE,
    INVALID_EMAIL, INVALID_PHONE, INVALID_COMPANY_NAME
}