spring:
  application:
    name: practice-manager

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG